# Symlink to this file from ~/.bashrc

. ~/documents/projects/dotfiles/dotfiles/bash/env
. ~/documents/projects/dotfiles/dotfiles/bash/config
. ~/documents/projects/dotfiles/dotfiles/bash/aliases
. ~/documents/projects/dotfiles/dotfiles/bash/prompt
