# Symlink to this file from ~/.bash_profile

. ~/projects/dotfiles/dotfiles/bash/env
. ~/projects/dotfiles/dotfiles/bash/config
. ~/projects/dotfiles/dotfiles/bash/aliases
. ~/projects/dotfiles/dotfiles/bash/prompt